version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: social_net_back
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db


volumes:
  postgres_data:
  static_volume:
  media_volume:
